import {synthesize} from './synthesis.js'; // Frozen: approved original A/B/C sounds must not change.
const $=id=>document.getElementById(id);
const [rows,designs,seed]=await Promise.all(['queue.json','designs.json','confirmed-seed.json'].map(f=>fetch('/tools/sound-review/'+f).then(r=>r.json())));
let disk;try{const res=await fetch('/__sound-review/state');if(!res.ok)throw Error();disk=await res.json();}catch{disk=seed;}
const key='heat-chase-sound-review-v2';let local;try{local=JSON.parse(localStorage.getItem(key)||'null');}catch{}
let decisions={...disk.decisions};if(local&&(!disk.savedAt||local.savedAt>disk.savedAt))decisions={...decisions,...local.decisions};
// Recover approvals made in the original page after the snapshot, on first migration only.
if(!disk.savedAt&&!local){try{const old=JSON.parse(localStorage.getItem('heat-chase-sound-review-v1')||'{}');for(const [id,d] of Object.entries(old)){if(d.updatedAt>(decisions[id]?.updatedAt??''))decisions[id]={...decisions[id],...d,designVersion:d.choice?.startsWith('option-')?'legacy-v1':d.designVersion};}}catch{}}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const approved=d=>!!d?.choice&&d.choice!=='needs-replacement';
let mode='remaining',selected,media,frame,context,source,gain,timer,token=0,pendingPreview,saveChain=Promise.resolve();const unlocked=new Set(),legacyCache=new Map();
const setMessage=s=>$('message').textContent=s;
const choiceName=d=>!d?'Not selected':d.choice==='keep-current'?'Current sound':d.choice==='own-file'?'Your file':d.choice==='silent'?'Silence':d.choice?.startsWith('design:')?designs[d.choice.slice(7)]?.name??'Custom design':d.choice?.startsWith('option-')?`Previously approved option ${'ABC'[Number(d.choice.slice(-1))]} · preserved exactly`:'Needs replacement';
function persist(){const state={version:2,savedAt:new Date().toISOString(),decisions:structuredClone(decisions)};try{localStorage.setItem(key,JSON.stringify(state));}catch{}
 saveChain=saveChain.catch(()=>{}).then(async()=>{const res=await fetch('/__sound-review/state',{method:'PUT',headers:{'Content-Type':'application/json','X-Sound-Review':'local'},body:JSON.stringify(state)});if(!res.ok)throw Error('Save failed');}).catch(()=>setMessage('Saved in this browser; project save unavailable. Export a backup before closing.'));return saveChain;}
function filtered(){const q=$('search').value.toLowerCase(),scope=$('scope').value;return rows.filter(r=>{const done=approved(decisions[r.id])&&!unlocked.has(r.id);return (mode==='confirmed'?done:!done)&&(mode==='confirmed'||scope==='all'||(scope==='core'?!['Music','Voices','Other effects'].includes(r.group):scope===r.group))&&(!q||`${r.title} ${r.purpose}`.toLowerCase().includes(q));});}
function list(){const queue=filtered(),saved=rows.filter(r=>approved(decisions[r.id])).length;$('queue-title').textContent=mode==='confirmed'?'Confirmed sounds':'Remaining decisions';$('progress').textContent=`${saved} confirmed · ${queue.length} ${mode==='confirmed'?'shown':'left in this section'}`;$('remaining').classList.toggle('primary',mode==='remaining');$('confirmed').classList.toggle('primary',mode==='confirmed');$('list').innerHTML=queue.map(r=>`<button data-row="${esc(r.id)}" class="${selected?.id===r.id?'active':''}">${mode==='confirmed'?'✓ ':''}${esc(r.title)}<small>${mode==='confirmed'?esc(choiceName(decisions[r.id])):esc(r.group)}</small></button>`).join('')||'<p>No sounds left in this section.</p>';}
function chooseNext(){selected=filtered()[0]??null;list();detail();}
function approve(choice,extra={}){if(!selected)return;const title=selected.title;decisions[selected.id]={...decisions[selected.id],...extra,choice,updatedAt:new Date().toISOString()};unlocked.delete(selected.id);void persist();stop(false);chooseNext();setMessage(`Confirmed: ${title}. Saved to this review; next sound is ready.`);}
function detail(){const r=selected;if(!r){$('detail').innerHTML=`<div class="card"><h2>${mode==='confirmed'?'No confirmed sounds in this search.':'You are caught up here.'}</h2><p>Choose another section, or open Confirmed to listen to your saved sounds.</p></div>`;return;}
 const d=decisions[r.id]||{},locked=approved(d)&&!unlocked.has(r.id);
 $('detail').innerHTML=`<span class="badge">${locked?'✓ Confirmed — exact selection preserved':r.group==='Symbols'?'One sound for this symbol':'Choose one sound'}</span><h2>${esc(r.title)}</h2><p>${esc(r.purpose)}</p>${locked?`
 <div class="card approved"><h3>${esc(choiceName(d))}</h3><p>${esc(d.fileName||'This approval is saved. You do not need to decide again.')}</p>${d.choice==='silent'?'<p>This moment will remain silent.</p>':'<button id="play-approved" class="primary">▶ Play confirmed sound</button>'}<button id="reopen">Change this choice</button></div>`:`
 ${r.current?`<div class="current-line"><button id="current">▶ Current sound</button><button id="keep">Keep current & next →</button></div>`:'<p class="muted">This moment needs a sound. Pick one of these two designs.</p>'}
 ${r.designs.length?`<div class="options two">${r.designs.map((id,i)=>{const s=designs[id];return `<article class="card"><small>OPTION ${i+1} · ${s.duration.toFixed(2)} SEC</small><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><button data-listen="${id}" class="primary">▶ Listen</button><button data-approve="${id}">Approve & next →</button></article>`;}).join('')}</div>`:'<div class="card"><p>Keep the current recording or add your own below. No generic synthesized substitute is offered for music, voices, or this loop.</p></div>'}
 <div class="actions"><button id="silent">No sound for this moment</button><button id="skip">Decide later →</button></div>`}
 <details ${d.candidateAsset?'open':''}><summary>Use my own file / leave feedback</summary><div class="card"><label>Add an audio file<input id="upload" type="file" accept="audio/*"></label><p class="muted">Stored locally in the project. No reattaching after reload.</p>${d.candidateAsset?`<p>${esc(d.candidateName)}</p><button id="candidate-play">▶ Listen to my file</button><button id="candidate-approve">Approve my file & next →</button>`:''}<label>What needs changing?<textarea id="notes" placeholder="Describe what you want to hear…">${esc(d.notes||'')}</textarea></label></div></details>`;
 const on=(id,fn)=>{if($(id))$(id).onclick=fn;};
 on('current',()=>playCurrent(r));on('keep',()=>approve('keep-current'));on('silent',()=>approve('silent'));on('skip',()=>{const queue=filtered(),i=queue.findIndex(x=>x.id===r.id);selected=queue[(i+1)%queue.length];stop(false);list();detail();});
 on('play-approved',()=>playApproved(r,d));on('reopen',()=>{unlocked.add(r.id);mode='remaining';$('scope').value='all';list();detail();});
 document.querySelectorAll('[data-listen]').forEach(b=>b.onclick=()=>playFile(designs[b.dataset.listen].url,designs[b.dataset.listen].name));
 document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approve('design:'+b.dataset.approve,{designVersion:'authored-v2'}));
 $('notes').oninput=e=>{decisions[r.id]={...decisions[r.id],notes:e.target.value};void persist();};
 $('upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024){setMessage('Please choose an audio file under 20 MB.');return;}setMessage('Saving your audio file…');try{const res=await fetch('/__sound-review/upload?name='+encodeURIComponent(file.name),{method:'POST',headers:{'X-Sound-Review':'local','Content-Type':'application/octet-stream'},body:file});const data=await res.json();if(!res.ok)throw Error(data.error);decisions[r.id]={...decisions[r.id],candidateAsset:data.url,candidateName:file.name};await persist();if(selected?.id===r.id)detail();setMessage('File saved. Listen, then approve it.');}catch(err){setMessage('Could not save the file: '+String(err));}};
 on('candidate-play',()=>playFile(d.candidateAsset,d.candidateName));on('candidate-approve',()=>approve('own-file',{assetUrl:d.candidateAsset,fileName:d.candidateName,candidateAsset:null,candidateName:null}));
}
function stop(announce=true){token++;clearTimeout(timer);if(source){try{source.stop();}catch{}source=null;}if(media){media.pause();media.removeAttribute('src');media.load();media=null;}if(frame){frame.contentWindow?.postMessage({action:'stop'},location.origin);frame.remove();frame=null;}pendingPreview=null;if(announce)setMessage('Playback stopped. Your choices are saved.');}
async function playFile(url,label){stop(false);const request=token;const player=new Audio(url);media=player;player.volume=Number($('volume').value);try{await player.play();if(token!==request)return;setMessage('Playing: '+label);timer=setTimeout(()=>stop(false),12000);}catch(e){if(request===token)setMessage('Playback failed: '+String(e));}}
function playCurrent(r){if(!r.current)return;if(r.current.kind==='file')return playFile(r.current.url,r.title);stop(false);pendingPreview=r;frame=document.createElement('iframe');frame.hidden=true;frame.allow='autoplay';frame.src='/tools/sound-review/preview.html';document.body.append(frame);setMessage('Loading current sound…');timer=setTimeout(()=>stop(false),12000);}
async function playApproved(r,d){if(d.choice==='silent')return;if(d.choice==='own-file')return playFile(d.assetUrl,d.fileName);if(d.choice==='keep-current')return playCurrent(r);if(d.choice.startsWith('design:')){const s=designs[d.choice.slice(7)];return playFile(s.url,s.name);}
 if(d.choice.startsWith('option-')){stop(false);const request=token;try{context??=new AudioContext();await context.resume();const variant=Number(d.choice.slice(-1)),key=r.profile+'-'+variant;if(!legacyCache.has(key))legacyCache.set(key,synthesize(r.profile,variant));const buffer=await legacyCache.get(key);if(token!==request)return;source=context.createBufferSource();source.buffer=buffer;gain=context.createGain();gain.gain.value=Number($('volume').value);source.connect(gain).connect(context.destination);const playing=source;playing.onended=()=>{playing.disconnect();if(source===playing)source=null;};source.start();setMessage(`Playing your original approved option ${'ABC'[variant]}: ${r.title}`);}catch(e){setMessage(String(e));}}
}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame?.contentWindow)return;if(e.data.type==='preview-ready')frame.contentWindow.postMessage({action:'play',current:pendingPreview?.current,volume:Number($('volume').value)},location.origin);if(e.data.type==='preview-playing')setMessage('Playing: '+pendingPreview?.title);if(e.data.type==='preview-error')setMessage(e.data.message);});
for(const id of ['search','scope'])$(id).oninput=()=>{stop(false);chooseNext();};
 $('remaining').onclick=()=>{mode='remaining';$('search').value='';stop(false);chooseNext();};$('confirmed').onclick=()=>{mode='confirmed';$('search').value='';stop(false);chooseNext();};
 $('list').onclick=e=>{const b=e.target.closest('[data-row]');if(b){stop(false);selected=rows.find(r=>r.id===b.dataset.row);list();detail();}};
 $('stop').onclick=()=>stop();$('volume').oninput=()=>{const v=Number($('volume').value);if(media)media.volume=v;if(gain)gain.gain.value=v;frame?.contentWindow?.postMessage({action:'volume',volume:v},location.origin);};
 $('export').onclick=()=>{let text=$('backup-json');if(!text){text=document.createElement('textarea');text.id='backup-json';text.readOnly=true;text.setAttribute('aria-label','Review backup JSON');$('export').after(text);}text.value=JSON.stringify({version:2,decisions},null,2);text.select();};
 $('archive').innerHTML=seed.archived.map(r=>`<p>${esc(r.title)}: ${esc(choiceName(decisions[r.id]))}. Preserved in backup; merged out of the symbol review after your one-sound request.</p>`).join('');
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop(false);});window.addEventListener('pagehide',()=>{stop(false);void context?.close();});
 chooseNext();setMessage('Your 25 previous choices are preserved. Pistol is trimmed to one shot. Start with the remaining symbols.');void persist();
