import { styles,synthesize,wav } from './synthesis.js';
const rows=await fetch('/tools/sound-review/catalog.json').then(r=>r.json());
const $=id=>document.getElementById(id), key='heat-chase-sound-review-v1';
let decisions={};try{decisions=JSON.parse(localStorage.getItem(key)||'{}');}catch{}
let selected=rows[0], context,source,gain,frame,media,stopTimer,token=0;
const uploads=new Map(),cache=new Map();
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function message(text){$('message').textContent=text;}
function save(){try{localStorage.setItem(key,JSON.stringify(decisions));}catch{message('Browser storage unavailable. Export decisions to keep them.');}list();}
function decide(value){decisions[selected.id]={...decisions[selected.id],choice:value,updatedAt:new Date().toISOString()};save();detail();}
function filtered(){const q=$('search').value.toLowerCase();return rows.filter(r=>(!$('group').value||r.group===$('group').value)&&(!q||`${r.title} ${r.purpose} ${r.status}`.toLowerCase().includes(q))&&(!$('pending').checked||!decisions[r.id]?.choice));}
function list(){const visible=filtered();$('progress').textContent=`${rows.filter(r=>decisions[r.id]?.choice).length} / ${rows.length} decisions · ${visible.length} shown`;$('list').innerHTML=visible.map(r=>`<button data-id="${escape(r.id)}" class="${r.id===selected.id?'active':''}">${decisions[r.id]?.choice?'✓ ':''}${escape(r.title)}<small>${escape(r.status)}</small></button>`).join('');}
function brief(r){return `Design an isolated ${r.title.toLowerCase()} sound for a neon Miami heist game. Purpose: ${r.purpose} ${r.profile==='source'?'For voices/music, agree performance or musical direction first.':'Dry, clean attack, clear on phone speakers, controlled low end, no clipping, no voice or background music. Provide a short tail and leave space for other effects.'} Match the visible action; no long silence before the cue. Supply WAV plus source/license information. Looping cues need seamless loop points and a separate ending.`;}
function detail(){const r=selected,d=decisions[r.id]||{};
 $('detail').innerHTML=`<span class="badge">${escape(r.status)}</span><h2>${escape(r.title)}</h2><p>${escape(r.purpose)}</p><div class="card"><h3>1. Hear the current sound</h3>${r.current?`<button id="current" class="primary">▶ Play current ${r.current.kind==='file'?'file':'effect'}</button><p class="muted">${r.current.kind==='file'?'Raw source preview, capped at 12 seconds. In-game pitch, trimming, layering and volume may differ.':'Runs the current game sound code in isolation. Normal-speed demonstration; no game round is started.'}</p>`:'<p>No dedicated current preview for this moment. Read the status: it may be missing, unhandled, or an optional proposal.</p>'}<div class="actions">${r.current?'<button id="keep">Keep current</button>':''}<button id="replace">Replace / explore options</button><button id="silent">Keep this moment silent</button></div></div>
 <h3>2. Compare directions</h3><p class="muted">Three reusable design families, tailored to this cue type. These are audition sketches, not final mastered assets.</p>${r.profile==='source'?'<div class="card"><p>This entry needs a recording, music, or voice brief. Use the brief below to find or generate alternatives, then attach your choice.</p></div>':`<div class="options">${styles.map((s,i)=>`<div class="card ${d.choice==='option-'+i?'selected':''}"><h3>${s.name}</h3><p>${s.description}</p><button data-play="${i}">▶ Listen</button><button data-choose="${i}">Choose ${'ABC'[i]}</button><button data-download="${i}">WAV ↓</button></div>`).join('')}</div>`}
 <div class="card"><h3>3. Or bring your own</h3><input id="upload" type="file" accept="audio/*" aria-label="Attach your own sound"><p class="muted">${escape(d.fileName||'No file attached.')} ${d.fileName&&!uploads.has(r.id)?'Reattach this file to audition it after reload.':''} Files stay on your computer; exports include their names, not audio.</p><button id="own" ${uploads.has(r.id)?'':'disabled'}>▶ Play your file</button><button id="choose-own" ${uploads.has(r.id)?'':'disabled'}>Choose your file</button><label>Feedback / source link / license<textarea id="notes" placeholder="Too sharp? More metal? Shorter tail? Paste a source link here.">${escape(d.notes||'')}</textarea></label></div>
 <details><summary>Sound brief and code evidence</summary><pre>${escape(brief(r))}</pre><button id="copy">Copy brief</button><p class="muted">${escape(r.evidence)}</p></details><p>Decision: <strong>${escape(d.choice||'Not decided')}</strong></p><div class="actions"><button id="previous">← Previous</button><button id="next" class="primary">Next sound →</button><button id="reset">Clear this decision</button></div>`;
 const bind=(id,fn)=>{if($(id))$(id).onclick=fn;};
 bind('current',()=>previewCurrent(r));bind('keep',()=>decide('keep-current'));bind('replace',()=>decide('needs-replacement'));bind('silent',()=>decide('silent'));
 document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>previewOption(r,Number(b.dataset.play)));
 document.querySelectorAll('[data-choose]').forEach(b=>b.onclick=()=>decide('option-'+b.dataset.choose));
 document.querySelectorAll('[data-download]').forEach(b=>b.onclick=async()=>{try{download(wav(await getBuffer(r,Number(b.dataset.download))),`${r.id}-${'ABC'[Number(b.dataset.download)]}.wav`);}catch(e){message(String(e));}});
 $('notes').oninput=e=>{decisions[r.id]={...decisions[r.id],notes:e.target.value};save();};
 $('upload').onchange=e=>{const f=e.target.files[0];if(!f)return;const old=uploads.get(r.id);if(old)URL.revokeObjectURL(old);uploads.set(r.id,URL.createObjectURL(f));decisions[r.id]={...decisions[r.id],fileName:f.name};save();detail();};
 bind('own',()=>playFile(uploads.get(r.id),'Your file'));bind('choose-own',()=>decide('own-file'));bind('copy',async()=>{try{await navigator.clipboard.writeText(brief(r));message('Brief copied.');}catch{message('Copy unavailable: select the brief text to copy manually.');}});
 bind('previous',()=>move(-1));bind('next',()=>move(1));bind('reset',()=>{delete decisions[r.id];save();detail();});
}
function move(dir){const queue=filtered(),index=queue.findIndex(r=>r.id===selected.id);selected=queue[Math.max(0,Math.min(queue.length-1,index+dir))]||selected;stop();list();detail();}
function stop(){token++;clearTimeout(stopTimer);source?.stop();source=null;if(media){media.pause();media.src='';media=null;}if(frame){frame.contentWindow?.postMessage({action:'stop'},location.origin);frame.remove();frame=null;}message('Audio stopped. Decisions remain saved.');}
function limit(){stopTimer=setTimeout(stop,12000);}
async function playFile(url,label){stop();const request=token;media=new Audio(url);media.volume=Number($('volume').value);try{await media.play();if(request!==token)return;message(`Playing ${label} · maximum 12 seconds`);limit();}catch(e){if(request===token)message('Could not play this file: '+String(e));}}
async function getBuffer(r,v){const k=r.profile+'-'+v;if(!cache.has(k))cache.set(k,synthesize(r.profile,v));return cache.get(k);}
async function previewOption(r,v){stop();const request=token;try{context??=new AudioContext();await context.resume();const buffer=await getBuffer(r,v);if(request!==token)return;source=context.createBufferSource();source.buffer=buffer;gain=context.createGain();gain.gain.value=Number($('volume').value);source.connect(gain).connect(context.destination);const voice=source;voice.onended=()=>{voice.disconnect();if(source===voice)source=null;};source.start();message(`Playing ${styles[v].name} · ${r.title}`);}catch(e){message(String(e));}}
function previewCurrent(r){if(r.current.kind==='file')return playFile(r.current.url,r.title);stop();frame=document.createElement('iframe');frame.hidden=true;frame.allow='autoplay';frame.src='/tools/sound-review/preview.html';document.body.append(frame);message('Loading current game sound…');limit();}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame?.contentWindow)return;if(e.data.type==='preview-ready')frame.contentWindow.postMessage({action:'play',current:selected.current,volume:Number($('volume').value)},location.origin);if(e.data.type==='preview-playing')message(`Playing current effect · ${selected.title}`);if(e.data.type==='preview-error')message(e.data.message);});
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
for(const g of new Set(rows.map(r=>r.group))){const o=document.createElement('option');o.value=g;o.textContent=g;$('group').append(o);}
for(const id of ['search','group','pending'])$(id).addEventListener('input',list);
 $('list').onclick=e=>{const b=e.target.closest('[data-id]');if(!b)return;stop();selected=rows.find(r=>r.id===b.dataset.id);list();detail();};
 $('stop').onclick=stop;$('volume').oninput=()=>{const v=Number($('volume').value);if(gain)gain.gain.value=v;if(media)media.volume=v;frame?.contentWindow?.postMessage({action:'volume',volume:v},location.origin);};
 $('export').onclick=()=>{
  const data=JSON.stringify({version:1,exportedAt:new Date().toISOString(),decisions},null,2);
  let fallback=$('export-copy');
  if(!fallback){fallback=document.createElement('textarea');fallback.id='export-copy';fallback.setAttribute('aria-label','Exported decisions JSON');fallback.readOnly=true;$('message').after(fallback);}
  fallback.value=data;
  download(new Blob([data],{type:'application/json'}),'heat-chase-sound-decisions.json');
  message('Export prepared. If the browser does not download it, copy the JSON below and send it in chat.');
 };
 $('import').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.version!==1||!data.decisions||typeof data.decisions!=='object')throw new Error('Invalid review file');for(const r of rows){const d=data.decisions[r.id];if(d&&typeof d==='object')decisions[r.id]={choice:['keep-current','needs-replacement','silent','option-0','option-1','option-2','own-file'].includes(d.choice)?d.choice:undefined,notes:String(d.notes||''),fileName:d.fileName?String(d.fileName):undefined};}save();detail();message('Decisions imported. Reattach custom audio files to hear them.');}catch(err){message('Import failed: '+String(err));}};
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',()=>{stop();void context?.close();});list();detail();
